<?xml version="1.0" encoding="UTF-8" ?>

<!-- 엘리먼트 타입 - EMPTY -->

<!DOCTYPE books [
<!ELEMENT books (book)*>
<!ELEMENT book (title,author+,press,page,description?,photo*,(cd|tape|usb)?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT press (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT cd EMPTY>
<!ELEMENT tape EMPTY>
<!ELEMENT usb EMPTY>
]>

<books>
    <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <press>cccc</press>
        <page>300</page>
    </book>
    <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <press>cccc</press>
        <page>300</page>
        <cd/>
    </book>
     <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <press>cccc</press>
        <page>300</page>
        <tape/>
    </book>
     <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <press>cccc</press>
        <page>300</page>
        <usb/>
    </book>
     <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <press>cccc</press>
        <page>300</page>
        <usb/>
        <cd/>
    </book>
     
</books> 

