<?xml version="1.0" encoding="UTF-8" ?>

<!-- 엘리먼트 타입 -->

<!DOCTYPE books [
<!ELEMENT books (book)*>
<!ELEMENT book (title,author+,press,page,description?,photo*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT press (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
]>

<books>
    <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <press>cccc</press>
        <page>300</page>
    </book>
    <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <author>okok</author>
        <press>cccc</press>
        <page>200</page>
        <description>okokok</description>
        <photo>a1.gif</photo>
    </book>
     <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <press>cccc</press>
        <page>200</page>
        <description>okokok</description>
        <photo>a1.gif</photo>
        <photo>a2.gif</photo>
    </book>
</books> 

